//data.js

export const categories = [
    "보드게임·TRPG",
    "디지털게임",
    "웹툰·만화",
    "웹툰 리소스",
    "디자인 문구",
    "캐릭터·굿즈",
    "홈·리빙",
    "테크·가전",
    "반려동물",
    "푸드",
    "향수·뷰티",
    "의류",
    "잡화",
    "주얼리",
    "출판",
    "디자인",
    "예술",
    "사진",
    "음악",
    "영화·비디오",
    "공연",
  ];
  
  export const banners = [
    {
      id: 0,
      title: "제철 과일로 돌아왔다\n치아가 환영하는 사탕",
      sub_title: "수박, 망고, 애플쥬스까지 여름 한정 에디션",
      text_color: "black",
      url: "https://tumblbug.com/xylocubesummer",
    },
    {
      id: 1,
      title: "둘 다 입긴 덥고 습해\n속옷과 바지를 하나로!",
      sub_title: "특수 설계로 속 안이 보이지 않는 트렁크",
      text_color: "black",
      url: "https://tumblbug.com/inafree",
    },
    {
      id: 2,
      title: "나의 작가 덕후지수는?\n김초엽 영역 덕력평가",
      sub_title: "한 권으로 알아보는 김초엽의 작품 세계",
      text_color: "white",
      url: "https://tumblbug.com/mdlabpress6",
    },
    {
      id: 3,
      title: "후원자가 반응하는\n패션 사진 촬영법",
      sub_title: "누적 펀딩 2억 달성한 창현의 촬영 가이드",
      text_color: "white",
      url: "https://brunch.co.kr/@tumblbug/204",
    },
  ];
  
  export const popular_projects = [
    {
      id: 0,
      title: "입에서 굴릴수록 치아가 건강해지는 마법의 사탕, 자일로큐브",
      category: "푸드",
      creator: "mintea",
      sponsorship_rate: 12202,
      url: "https://tumblbug.com/xylocubesummer",
    },
    {
      id: 1,
      title: "읽기 쉽고 화려한 '덕질 타로' [로제딕]",
      category: "디자인",
      creator: "쥬나",
      sponsorship_rate: 1154,
      url: "https://tumblbug.com/rosethic",
    },
    {
      id: 2,
      title: "이것만 알아도 대화가 통한다! IT/기획/개발/마케팅 용어",
      category: "출판",
      creator: "그로스쿨",
      sponsorship_rate: 5873,
      url: "https://tumblbug.com/it_terms",
    },
    {
      id: 3,
      title: "[섹스 온 더 비치] 너의 사랑을 이뤄줄 은밀한 칵테일향기",
      category: "향수·뷰티",
      creator: "퍼퓸바",
      sponsorship_rate: 458,
      url: "https://tumblbug.com/perfumebar",
    },
    {
      id: 4,
      title: "넥타르와 함께 즐긴, 승도복숭아를 품은 '암브로시아 향수'",
      category: "향수·뷰티",
      creator: "소아모",
      sponsorship_rate: 247,
      url: "https://tumblbug.com/ambrosia",
    },
    {
      id: 5,
      title: "[타로 퍼퓸] 달콤한 라즈베리빛 & 잔잔한 바이올렛빛 사랑",
      category: "향수·뷰티",
      creator: "닉스",
      sponsorship_rate: 322,
      url: "https://tumblbug.com/lefaytarot01",
    },
    {
      id: 6,
      title: "2D처럼 자연스럽게! 그대로 쓰는 3D < 프릴&레이스 >",
      category: "웹툰 리소스",
      creator: "팀 플래터",
      sponsorship_rate: 168,
      url: "https://tumblbug.com/platter_frill",
    },
    {
      id: 7,
      title: "네이버웹툰 <도롱이> 단행본 1-5권 세트 제작",
      category: "웹툰·만화",
      creator: "네이버웹툰",
      sponsorship_rate: 1908,
      url: "https://tumblbug.com/dolongi",
    },
  ];
  
  export const notable_projects = [
    {
      id: 0,
      title: "악필은 고칠 수 있어. 그것도 매우 쉽게! 글씨 교정 노트",
      category: "디자인 문구",
      creator: "Wearingeul(글입다)",
      sponsorship_rate: 1717,
      url: "https://tumblbug.com/better",
    },
    {
      id: 1,
      title: "스타급 성우진과 함께 하는 <집이 없어> 오디오웹툰 시즌1",
      category: "웹툰·만화",
      creator: "네이버웹툰",
      sponsorship_rate: 152,
      url: "https://tumblbug.com/wananaudio1",
    },
    {
      id: 2,
      title: "참치 아니었어? 식물성참치 UNTUNA! 이제는 대체참치다",
      category: "푸드",
      creator: "UNFISK109",
      sponsorship_rate: 1723,
      url: "https://tumblbug.com/untuna",
    },
    {
      id: 3,
      title: "세상으로 생명을 배달하는 [숲 속의 배달부]",
      category: "디지털 게임",
      creator: "나라이엔씨",
      sponsorship_rate: 113,
      url: "https://tumblbug.com/deliverykore",
    },
    {
      id: 4,
      title: "감성까지 충전하는 다재다능한 5 in 1 충전기 C.C",
      category: "테크·가전",
      creator: "주식회사 하만",
      sponsorship_rate: 34,
      url: "https://tumblbug.com/cablecutter",
    },
    {
      id: 5,
      title: "귀신들의 소망을 그린 만화 [꿈의 유실물]",
      category: "웹툰·만화",
      creator: "박인주",
      sponsorship_rate: 299,
      url: "https://tumblbug.com/missingdreams",
    },
    {
      id: 6,
      title: "자연이 만든 아름다운 모양, 조약돌처럼 귀여운 향수목걸이",
      category: "주얼리",
      creator: "SUITTE(수티)",
      sponsorship_rate: 1463,
      url: "https://tumblbug.com/suitte7",
    },
    {
      id: 7,
      title: "한강을 제대로 즐기고 싶다면, <한강의 대교>",
      category: "출판",
      creator: "초점, magazine focus",
      sponsorship_rate: 134,
      url: "https://tumblbug.com/magazine_focus",
    },
  ];